# Generated by Django 3.1.1 on 2020-09-28 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_worddoc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddoc',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
