# Generated by Django 3.1.1 on 2020-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_worddoc_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberedDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('doc_file', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='worddoc',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
