# Generated by Django 3.1.1 on 2020-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201001_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddoc',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
