# Generated by Django 3.1.1 on 2020-10-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201001_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberedDoc',
        ),
    ]
